use_frameworks!

target 'ChatTextView_Example' do
  pod 'ChatTextView', :path => '../'
  pod 'UnderKeyboard'

  target 'ChatTextView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Quick'
    pod 'Nimble'
  end
end
