use_frameworks!

target 'ChatTextView_Example' do
  pod 'ChatTextView', :path => '../'

  target 'ChatTextView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
